SELECT FULL_NAME, CARD_ID, MAGSTRIPE, EXP_DATE,'TNG' AS TNG, SIGUR_PHOTO_SYNC.PHOTO_BIN

FROM(select FULL_NAME, CARD_ID, MAGSTRIPE, MAX(UHU) as EXP_DATE

from (SELECT CARDS.last_name||' '||CARDS.first_name||' '||CARDS.second_name AS FULL_NAME,

SUBSCRIPTION_ACCOUNTING.card_id,

CARDS.magstripe,

SUBSCRIPTION_ACCOUNTING.status,

SUBSCRIPTION_ACCOUNTING.expiration_date,

subscription_accounting.mmshp_end_date,

CURRENT_DATE AS TODAY_DATE,

CASE

WHEN SUBSCRIPTION_ACCOUNTING.status = 2 THEN

CASE

WHEN SUBSCRIPTION_ACCOUNTING.IS_MEMBERSHIP = 0 THEN SUBSCRIPTION_ACCOUNTING.expiration_date

ELSE

CASE

WHEN SUBSCRIPTION_ACCOUNTING.expiration_date > subscription_accounting.mmshp_end_date THEN SUBSCRIPTION_ACCOUNTING.expiration_date

ELSE subscription_accounting.mmshp_end_date

END

END

WHEN SUBSCRIPTION_ACCOUNTING.status = 3 THEN subscription_accounting.mmshp_end_date

ELSE TO_DATE(current_date, 'DD.MM.YY')

END as UHU

FROM SUBSCRIPTION_ACCOUNTING,CARDS where

SUBSCRIPTION_ACCOUNTING.card_id = CARDS.card_id

AND CARDS.magstripe IS NOT NULL

AND length(CARDS.magstripe ) = 8

AND SUBSCRIPTION_ACCOUNTING.mmshp_end_date > ADD_MONTHS(CURRENT_DATE, -3)

AND SUBSCRIPTION_ACCOUNTING.expiration_date > ADD_MONTHS(CURRENT_DATE, -3))

GROUP BY FULL_NAME,CARD_ID, MAGSTRIPE)

INNER JOIN SIGUR_PHOTO_SYNC ON CARD_ID = SIGUR_PHOTO_SYNC.PHOTO_ID

ORDER BY FULL_NAME;